language: node_js

node_js:
- '10.10.0'

cache:
  directories:
  - node_modules

install:
- npm i -g yarn@1.16.0
- yarn install

script:
- yarn lint
- yarn test
- yarn typecheck
- yarn build

notifications:
  email: false
