language: node_js

node_js:
- '10.14.1'

cache:
  directories:
  - node_modules

install:
- npm i -g yarn@1.19.2
- yarn install

script:
- yarn lint
- yarn test
- yarn typecheck
- yarn build

notifications:
  email: false
